//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClientSoap.WSServerSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WSServerSoap.MetodosRCD")]
    public interface MetodosRCD {
        
        // CODEGEN: Generating message contract since element name nombreCompleto from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/MetodosRCD/ValidacionNombreRequest", ReplyAction="http://ws/MetodosRCD/ValidacionNombreResponse")]
        WSClientSoap.WSServerSoap.ValidacionNombreResponse ValidacionNombre(WSClientSoap.WSServerSoap.ValidacionNombreRequest request);
        
        // CODEGEN: Generating message contract since element name rut from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/MetodosRCD/ValidacionRutRequest", ReplyAction="http://ws/MetodosRCD/ValidacionRutResponse")]
        WSClientSoap.WSServerSoap.ValidacionRutResponse ValidacionRut(WSClientSoap.WSServerSoap.ValidacionRutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionNombre", Namespace="http://ws/", Order=0)]
        public WSClientSoap.WSServerSoap.ValidacionNombreRequestBody Body;
        
        public ValidacionNombreRequest() {
        }
        
        public ValidacionNombreRequest(WSClientSoap.WSServerSoap.ValidacionNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreCompleto;
        
        public ValidacionNombreRequestBody() {
        }
        
        public ValidacionNombreRequestBody(string nombreCompleto) {
            this.nombreCompleto = nombreCompleto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionNombreResponse", Namespace="http://ws/", Order=0)]
        public WSClientSoap.WSServerSoap.ValidacionNombreResponseBody Body;
        
        public ValidacionNombreResponse() {
        }
        
        public ValidacionNombreResponse(WSClientSoap.WSServerSoap.ValidacionNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ValidacionNombreResponseBody() {
        }
        
        public ValidacionNombreResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionRut", Namespace="http://ws/", Order=0)]
        public WSClientSoap.WSServerSoap.ValidacionRutRequestBody Body;
        
        public ValidacionRutRequest() {
        }
        
        public ValidacionRutRequest(WSClientSoap.WSServerSoap.ValidacionRutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionRutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dv;
        
        public ValidacionRutRequestBody() {
        }
        
        public ValidacionRutRequestBody(string rut, string dv) {
            this.rut = rut;
            this.dv = dv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionRutResponse", Namespace="http://ws/", Order=0)]
        public WSClientSoap.WSServerSoap.ValidacionRutResponseBody Body;
        
        public ValidacionRutResponse() {
        }
        
        public ValidacionRutResponse(WSClientSoap.WSServerSoap.ValidacionRutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionRutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public ValidacionRutResponseBody() {
        }
        
        public ValidacionRutResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetodosRCDChannel : WSClientSoap.WSServerSoap.MetodosRCD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosRCDClient : System.ServiceModel.ClientBase<WSClientSoap.WSServerSoap.MetodosRCD>, WSClientSoap.WSServerSoap.MetodosRCD {
        
        public MetodosRCDClient() {
        }
        
        public MetodosRCDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosRCDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosRCDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosRCDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClientSoap.WSServerSoap.ValidacionNombreResponse WSClientSoap.WSServerSoap.MetodosRCD.ValidacionNombre(WSClientSoap.WSServerSoap.ValidacionNombreRequest request) {
            return base.Channel.ValidacionNombre(request);
        }
        
        public string ValidacionNombre(string nombreCompleto) {
            WSClientSoap.WSServerSoap.ValidacionNombreRequest inValue = new WSClientSoap.WSServerSoap.ValidacionNombreRequest();
            inValue.Body = new WSClientSoap.WSServerSoap.ValidacionNombreRequestBody();
            inValue.Body.nombreCompleto = nombreCompleto;
            WSClientSoap.WSServerSoap.ValidacionNombreResponse retVal = ((WSClientSoap.WSServerSoap.MetodosRCD)(this)).ValidacionNombre(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClientSoap.WSServerSoap.ValidacionRutResponse WSClientSoap.WSServerSoap.MetodosRCD.ValidacionRut(WSClientSoap.WSServerSoap.ValidacionRutRequest request) {
            return base.Channel.ValidacionRut(request);
        }
        
        public bool ValidacionRut(string rut, string dv) {
            WSClientSoap.WSServerSoap.ValidacionRutRequest inValue = new WSClientSoap.WSServerSoap.ValidacionRutRequest();
            inValue.Body = new WSClientSoap.WSServerSoap.ValidacionRutRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.dv = dv;
            WSClientSoap.WSServerSoap.ValidacionRutResponse retVal = ((WSClientSoap.WSServerSoap.MetodosRCD)(this)).ValidacionRut(inValue);
            return retVal.Body.@return;
        }
    }
}
