//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSoap.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WebService.WSValidar")]
    public interface WSValidar {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreCompleto del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionNombreRequest", ReplyAction="http://ws/WSValidar/ValidacionNombreResponse")]
        ClienteSoap.WebService.ValidacionNombreResponse ValidacionNombre(ClienteSoap.WebService.ValidacionNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionNombreRequest", ReplyAction="http://ws/WSValidar/ValidacionNombreResponse")]
        System.Threading.Tasks.Task<ClienteSoap.WebService.ValidacionNombreResponse> ValidacionNombreAsync(ClienteSoap.WebService.ValidacionNombreRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionRutRequest", ReplyAction="http://ws/WSValidar/ValidacionRutResponse")]
        ClienteSoap.WebService.ValidacionRutResponse ValidacionRut(ClienteSoap.WebService.ValidacionRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionRutRequest", ReplyAction="http://ws/WSValidar/ValidacionRutResponse")]
        System.Threading.Tasks.Task<ClienteSoap.WebService.ValidacionRutResponse> ValidacionRutAsync(ClienteSoap.WebService.ValidacionRutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionNombre", Namespace="http://ws/", Order=0)]
        public ClienteSoap.WebService.ValidacionNombreRequestBody Body;
        
        public ValidacionNombreRequest() {
        }
        
        public ValidacionNombreRequest(ClienteSoap.WebService.ValidacionNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreCompleto;
        
        public ValidacionNombreRequestBody() {
        }
        
        public ValidacionNombreRequestBody(string nombreCompleto) {
            this.nombreCompleto = nombreCompleto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionNombreResponse", Namespace="http://ws/", Order=0)]
        public ClienteSoap.WebService.ValidacionNombreResponseBody Body;
        
        public ValidacionNombreResponse() {
        }
        
        public ValidacionNombreResponse(ClienteSoap.WebService.ValidacionNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ValidacionNombreResponseBody() {
        }
        
        public ValidacionNombreResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionRut", Namespace="http://ws/", Order=0)]
        public ClienteSoap.WebService.ValidacionRutRequestBody Body;
        
        public ValidacionRutRequest() {
        }
        
        public ValidacionRutRequest(ClienteSoap.WebService.ValidacionRutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionRutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dv;
        
        public ValidacionRutRequestBody() {
        }
        
        public ValidacionRutRequestBody(string rut, string dv) {
            this.rut = rut;
            this.dv = dv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionRutResponse", Namespace="http://ws/", Order=0)]
        public ClienteSoap.WebService.ValidacionRutResponseBody Body;
        
        public ValidacionRutResponse() {
        }
        
        public ValidacionRutResponse(ClienteSoap.WebService.ValidacionRutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionRutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public ValidacionRutResponseBody() {
        }
        
        public ValidacionRutResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSValidarChannel : ClienteSoap.WebService.WSValidar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSValidarClient : System.ServiceModel.ClientBase<ClienteSoap.WebService.WSValidar>, ClienteSoap.WebService.WSValidar {
        
        public WSValidarClient() {
        }
        
        public WSValidarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSValidarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSValidarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSValidarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.WebService.ValidacionNombreResponse ClienteSoap.WebService.WSValidar.ValidacionNombre(ClienteSoap.WebService.ValidacionNombreRequest request) {
            return base.Channel.ValidacionNombre(request);
        }
        
        public string ValidacionNombre(string nombreCompleto) {
            ClienteSoap.WebService.ValidacionNombreRequest inValue = new ClienteSoap.WebService.ValidacionNombreRequest();
            inValue.Body = new ClienteSoap.WebService.ValidacionNombreRequestBody();
            inValue.Body.nombreCompleto = nombreCompleto;
            ClienteSoap.WebService.ValidacionNombreResponse retVal = ((ClienteSoap.WebService.WSValidar)(this)).ValidacionNombre(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.WebService.ValidacionNombreResponse> ClienteSoap.WebService.WSValidar.ValidacionNombreAsync(ClienteSoap.WebService.ValidacionNombreRequest request) {
            return base.Channel.ValidacionNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.WebService.ValidacionNombreResponse> ValidacionNombreAsync(string nombreCompleto) {
            ClienteSoap.WebService.ValidacionNombreRequest inValue = new ClienteSoap.WebService.ValidacionNombreRequest();
            inValue.Body = new ClienteSoap.WebService.ValidacionNombreRequestBody();
            inValue.Body.nombreCompleto = nombreCompleto;
            return ((ClienteSoap.WebService.WSValidar)(this)).ValidacionNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.WebService.ValidacionRutResponse ClienteSoap.WebService.WSValidar.ValidacionRut(ClienteSoap.WebService.ValidacionRutRequest request) {
            return base.Channel.ValidacionRut(request);
        }
        
        public bool ValidacionRut(string rut, string dv) {
            ClienteSoap.WebService.ValidacionRutRequest inValue = new ClienteSoap.WebService.ValidacionRutRequest();
            inValue.Body = new ClienteSoap.WebService.ValidacionRutRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.dv = dv;
            ClienteSoap.WebService.ValidacionRutResponse retVal = ((ClienteSoap.WebService.WSValidar)(this)).ValidacionRut(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.WebService.ValidacionRutResponse> ClienteSoap.WebService.WSValidar.ValidacionRutAsync(ClienteSoap.WebService.ValidacionRutRequest request) {
            return base.Channel.ValidacionRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.WebService.ValidacionRutResponse> ValidacionRutAsync(string rut, string dv) {
            ClienteSoap.WebService.ValidacionRutRequest inValue = new ClienteSoap.WebService.ValidacionRutRequest();
            inValue.Body = new ClienteSoap.WebService.ValidacionRutRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.dv = dv;
            return ((ClienteSoap.WebService.WSValidar)(this)).ValidacionRutAsync(inValue);
        }
    }
}
