//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSoap.wsServicioCliente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="wsServicioCliente.WSValidar")]
    public interface WSValidar {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionRutRequest", ReplyAction="http://ws/WSValidar/ValidacionRutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSoap.wsServicioCliente.ValidacionRutResponse ValidacionRut(ClienteSoap.wsServicioCliente.ValidacionRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionRutRequest", ReplyAction="http://ws/WSValidar/ValidacionRutResponse")]
        System.Threading.Tasks.Task<ClienteSoap.wsServicioCliente.ValidacionRutResponse> ValidacionRutAsync(ClienteSoap.wsServicioCliente.ValidacionRutRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionNombreRequest", ReplyAction="http://ws/WSValidar/ValidacionNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteSoap.wsServicioCliente.ValidacionNombreResponse ValidacionNombre(ClienteSoap.wsServicioCliente.ValidacionNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSValidar/ValidacionNombreRequest", ReplyAction="http://ws/WSValidar/ValidacionNombreResponse")]
        System.Threading.Tasks.Task<ClienteSoap.wsServicioCliente.ValidacionNombreResponse> ValidacionNombreAsync(ClienteSoap.wsServicioCliente.ValidacionNombreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidacionRut", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidacionRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dv;
        
        public ValidacionRutRequest() {
        }
        
        public ValidacionRutRequest(string rut, string dv) {
            this.rut = rut;
            this.dv = dv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidacionRutResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidacionRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ValidacionRutResponse() {
        }
        
        public ValidacionRutResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidacionNombre", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidacionNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreCompleto;
        
        public ValidacionNombreRequest() {
        }
        
        public ValidacionNombreRequest(string nombreCompleto) {
            this.nombreCompleto = nombreCompleto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidacionNombreResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class ValidacionNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public ValidacionNombreResponse() {
        }
        
        public ValidacionNombreResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSValidarChannel : ClienteSoap.wsServicioCliente.WSValidar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSValidarClient : System.ServiceModel.ClientBase<ClienteSoap.wsServicioCliente.WSValidar>, ClienteSoap.wsServicioCliente.WSValidar {
        
        public WSValidarClient() {
        }
        
        public WSValidarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSValidarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSValidarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSValidarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.wsServicioCliente.ValidacionRutResponse ClienteSoap.wsServicioCliente.WSValidar.ValidacionRut(ClienteSoap.wsServicioCliente.ValidacionRutRequest request) {
            return base.Channel.ValidacionRut(request);
        }
        
        public bool ValidacionRut(string rut, string dv) {
            ClienteSoap.wsServicioCliente.ValidacionRutRequest inValue = new ClienteSoap.wsServicioCliente.ValidacionRutRequest();
            inValue.rut = rut;
            inValue.dv = dv;
            ClienteSoap.wsServicioCliente.ValidacionRutResponse retVal = ((ClienteSoap.wsServicioCliente.WSValidar)(this)).ValidacionRut(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.wsServicioCliente.ValidacionRutResponse> ClienteSoap.wsServicioCliente.WSValidar.ValidacionRutAsync(ClienteSoap.wsServicioCliente.ValidacionRutRequest request) {
            return base.Channel.ValidacionRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.wsServicioCliente.ValidacionRutResponse> ValidacionRutAsync(string rut, string dv) {
            ClienteSoap.wsServicioCliente.ValidacionRutRequest inValue = new ClienteSoap.wsServicioCliente.ValidacionRutRequest();
            inValue.rut = rut;
            inValue.dv = dv;
            return ((ClienteSoap.wsServicioCliente.WSValidar)(this)).ValidacionRutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSoap.wsServicioCliente.ValidacionNombreResponse ClienteSoap.wsServicioCliente.WSValidar.ValidacionNombre(ClienteSoap.wsServicioCliente.ValidacionNombreRequest request) {
            return base.Channel.ValidacionNombre(request);
        }
        
        public string[] ValidacionNombre(string nombreCompleto) {
            ClienteSoap.wsServicioCliente.ValidacionNombreRequest inValue = new ClienteSoap.wsServicioCliente.ValidacionNombreRequest();
            inValue.nombreCompleto = nombreCompleto;
            ClienteSoap.wsServicioCliente.ValidacionNombreResponse retVal = ((ClienteSoap.wsServicioCliente.WSValidar)(this)).ValidacionNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSoap.wsServicioCliente.ValidacionNombreResponse> ClienteSoap.wsServicioCliente.WSValidar.ValidacionNombreAsync(ClienteSoap.wsServicioCliente.ValidacionNombreRequest request) {
            return base.Channel.ValidacionNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSoap.wsServicioCliente.ValidacionNombreResponse> ValidacionNombreAsync(string nombreCompleto) {
            ClienteSoap.wsServicioCliente.ValidacionNombreRequest inValue = new ClienteSoap.wsServicioCliente.ValidacionNombreRequest();
            inValue.nombreCompleto = nombreCompleto;
            return ((ClienteSoap.wsServicioCliente.WSValidar)(this)).ValidacionNombreAsync(inValue);
        }
    }
}
