//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSSoapClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ServiceReference1.MetodosRCD")]
    public interface MetodosRCD {
        
        // CODEGEN: Generating message contract since element name nombreCompleto from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/MetodosRCD/ValidacionNombreRequest", ReplyAction="http://ws/MetodosRCD/ValidacionNombreResponse")]
        WSSoapClient.ServiceReference1.ValidacionNombreResponse ValidacionNombre(WSSoapClient.ServiceReference1.ValidacionNombreRequest request);
        
        // CODEGEN: Generating message contract since element name rut from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/MetodosRCD/ValidacionRutRequest", ReplyAction="http://ws/MetodosRCD/ValidacionRutResponse")]
        WSSoapClient.ServiceReference1.ValidacionRutResponse ValidacionRut(WSSoapClient.ServiceReference1.ValidacionRutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionNombre", Namespace="http://ws/", Order=0)]
        public WSSoapClient.ServiceReference1.ValidacionNombreRequestBody Body;
        
        public ValidacionNombreRequest() {
        }
        
        public ValidacionNombreRequest(WSSoapClient.ServiceReference1.ValidacionNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreCompleto;
        
        public ValidacionNombreRequestBody() {
        }
        
        public ValidacionNombreRequestBody(string nombreCompleto) {
            this.nombreCompleto = nombreCompleto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionNombreResponse", Namespace="http://ws/", Order=0)]
        public WSSoapClient.ServiceReference1.ValidacionNombreResponseBody Body;
        
        public ValidacionNombreResponse() {
        }
        
        public ValidacionNombreResponse(WSSoapClient.ServiceReference1.ValidacionNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public ValidacionNombreResponseBody() {
        }
        
        public ValidacionNombreResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionRut", Namespace="http://ws/", Order=0)]
        public WSSoapClient.ServiceReference1.ValidacionRutRequestBody Body;
        
        public ValidacionRutRequest() {
        }
        
        public ValidacionRutRequest(WSSoapClient.ServiceReference1.ValidacionRutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionRutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dv;
        
        public ValidacionRutRequestBody() {
        }
        
        public ValidacionRutRequestBody(string rut, string dv) {
            this.rut = rut;
            this.dv = dv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidacionRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidacionRutResponse", Namespace="http://ws/", Order=0)]
        public WSSoapClient.ServiceReference1.ValidacionRutResponseBody Body;
        
        public ValidacionRutResponse() {
        }
        
        public ValidacionRutResponse(WSSoapClient.ServiceReference1.ValidacionRutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ValidacionRutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public ValidacionRutResponseBody() {
        }
        
        public ValidacionRutResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MetodosRCDChannel : WSSoapClient.ServiceReference1.MetodosRCD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MetodosRCDClient : System.ServiceModel.ClientBase<WSSoapClient.ServiceReference1.MetodosRCD>, WSSoapClient.ServiceReference1.MetodosRCD {
        
        public MetodosRCDClient() {
        }
        
        public MetodosRCDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MetodosRCDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosRCDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MetodosRCDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSSoapClient.ServiceReference1.ValidacionNombreResponse WSSoapClient.ServiceReference1.MetodosRCD.ValidacionNombre(WSSoapClient.ServiceReference1.ValidacionNombreRequest request) {
            return base.Channel.ValidacionNombre(request);
        }
        
        public string ValidacionNombre(string nombreCompleto) {
            WSSoapClient.ServiceReference1.ValidacionNombreRequest inValue = new WSSoapClient.ServiceReference1.ValidacionNombreRequest();
            inValue.Body = new WSSoapClient.ServiceReference1.ValidacionNombreRequestBody();
            inValue.Body.nombreCompleto = nombreCompleto;
            WSSoapClient.ServiceReference1.ValidacionNombreResponse retVal = ((WSSoapClient.ServiceReference1.MetodosRCD)(this)).ValidacionNombre(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSSoapClient.ServiceReference1.ValidacionRutResponse WSSoapClient.ServiceReference1.MetodosRCD.ValidacionRut(WSSoapClient.ServiceReference1.ValidacionRutRequest request) {
            return base.Channel.ValidacionRut(request);
        }
        
        public bool ValidacionRut(string rut, string dv) {
            WSSoapClient.ServiceReference1.ValidacionRutRequest inValue = new WSSoapClient.ServiceReference1.ValidacionRutRequest();
            inValue.Body = new WSSoapClient.ServiceReference1.ValidacionRutRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.dv = dv;
            WSSoapClient.ServiceReference1.ValidacionRutResponse retVal = ((WSSoapClient.ServiceReference1.MetodosRCD)(this)).ValidacionRut(inValue);
            return retVal.Body.@return;
        }
    }
}
